### PR TITLE
Framerate fixes + other bug fixes

### PR DESCRIPTION
**Pull request by ActualMandM**
- fix camera follow and bump speed issues depending on framerate
 - vocals now sync up with the song
 - combo now counts correctly
 - fixes instant crash with newer polymod versions

don't worry about Main.hx having framerate set back to 60, the game will grab the current fps cap and will apply that once in-game

### CODE REVIEW

**Comment by DotWith** [comment]
The leaked week7 code

Put `import flixel.FlxG;` in import.hx

For CoolUtil use
```hx
public static function camLerpShit(ratio:Float):Float
{
	return FlxG.elapsed / 0.016666666666666666 * ratio;
}

public static function coolLerp(a:Float, b:Int, ratio:Float):Float
{
	return a + camLerpShit(ratio) * (b - a);
}
```

MainMenuState for update
I removed the camera follow and it still worked!
```hx
FlxG.camera.followLerp = CoolUtil.camLerpShit(0.06);
```

In PlayState
```hx
iconP1.setGraphicSize(Std.int(CoolUtil.coolLerp(iconP1.width, 150, 0.15)));
iconP2.setGraphicSize(Std.int(CoolUtil.coolLerp(iconP1.width, 150, 0.15)));
```
```hx
FlxG.camera.zoom = FlxMath.lerp(defaultCamZoom, FlxG.camera.zoom, 0.95);
camHUD.zoom = FlxMath.lerp(1, camHUD.zoom, 0.95);
```
stepHit
```hx
if (Math.abs(FlxG.sound.music.time - (Conductor.songPosition - Conductor.offset)) > 20
			|| (SONG.needsVoices && Math.abs(vocals.time - (Conductor.songPosition - Conductor.offset)) > 20))
{
	resyncVocals();
}
```
resyncVocals
```hx
if (_exiting)
	return;

vocals.pause();
FlxG.sound.music.play();
Conductor.songPosition = FlxG.sound.music.time + Conductor.offset;

if (vocalsFinished)
	return;

vocals.time = Conductor.songPosition;
vocals.play();
```

**Comment by DotWith** [comment]
So are you going to use? It's **b e t t e r**

**Comment by ActualMandM** [comment]
I'd rather not use leaked code, but thanks for the offer anyway.

**Comment by CryBitDev** [comment]
Seems good, will merge i guess.

**Comment by CryBitDev** [comment]
After reading the comments, i have decided for this to be put on hold, since it involves leaked week 7 code, which i don't like using.

**Comment by ActualMandM** [comment]
I did reverse-engineer the Javascript code, but I can close this down for now until 0.2.8's source code actually releases (and adjust the code when that happens too).

**Comment by CryBitDev** [comment]
No need, the mod is being ported to psych

**Comment by ActualMandM** [comment]
Ah yeah, to my knowledge Psych handles camera stuff a lot better compared to Kade

**Pull request closed without merging**
